#!/bin/bash

echo "sample-sub-handler: Received a request, processing..." >&2

#echo path, method and protocol info passed into this script from the root-handler, which should have been passed in as the request line.
read -r method path protocol
echo "sample-sub-handler: Received request with method: $method, path: $path, protocol: $protocol" >&2


body='{"status":"ok","handler":"sample-sub-handler","method":"'"$method"'","path":"'"$path"'","protocol":"'"$protocol"'"}'

printf "HTTP/1.1 200 OK\r\n"
printf "Content-Type: application/json\r\n"
printf "Content-Length: %s\r\n" "${#body}"
printf "Connection: close\r\n"
printf "\r\n"
printf "%s" "$body"

echo "sample-sub-handler: Response sent, closing connection." >&2