#!/bin/bash

# declare globals
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOCAT_PID=""
PROCESS_MONITOR_PID=""
PROCESS_USAGE_HISTORY_STATS_MMAP_FILE="/dev/shm/process_usage_history.json"
BASHLET_CONTEXT_KV_STORE_MMAP_FILE="/dev/shm/bashlet_context_kv_store.json"







# declare default server configuration globals, these WILL be overridden by values read from the main server configuration JSON file.
MAX_PROCESSES=50
MAX_PROCESS_RUNTIME=10
LISTEN_PORT=3333
AUTH_TOKEN_COOKIE_NAME="auth_token"
AUTH_TOKEN_EXPIRATION_MINUTES=30
ADMIN_USER_EMAIL=""


# source the config utils script to enable us to read and parse the server configuration JSON file.
source "${SCRIPT_DIR}/res/handlers/internal/utils/config-utils"


# trap exit
trap teardown EXIT INT TERM


startup() {
  echo "Starting Mocktail server..." >&2
  acquireScriptDependencies
  # applyServerFilePermissions # apply file permissions to all server files, including sub scripts, internal and system files.
  configureServer
  exportSharedVariables # export shared variables that the handler (sub)  scripts may need to reference.
  initialiseBashletEngine # call private helper function to initialise the BashletEngine.
  startProcessUsageMonitor # start the process usage monitor in the background to track the number of active processes over time.
  startListening 
 
}


teardown() {
  echo "Stopping Mocktail server..." >&2
  stopProcessUsageMonitor
  stopListening
  clearMMAPFiles
  echo "Mocktail server stopped." >&2
}

startListening(){

  echo "Starting Mocktail server on port $LISTEN_PORT..." >&2
  
  # spin up a socat process to start listening on the specified port taking care to specify our root handler subscript.
  # ensure the base64 annotation metadata is exported in this parent shell
  #export BASHLET_ANNOTATION_METADATA_BASE64

  ROOT_HANDLER="$SCRIPT_DIR/res/handlers/internal/root-handler"
    socat TCP-LISTEN:$LISTEN_PORT,reuseaddr,fork \
        EXEC:"timeout 10s bash $ROOT_HANDLER" &

  # immediately capture the socat PID so we can manage it lifecycle, especially for cleanup.
  SOCAT_PID=$!

  # log status message to indicate the server is running and listening for requests.
  echo "Mocktail server is running on port $LISTEN_PORT"

  # wait for the socat process to exit, which will happen when the server is stopped or if it encounters a critical error.
  wait "$SOCAT_PID"

}

stopListening(){

   echo "Stopping Mocktail server (PID: $SOCAT_PID)..." >&2

   if [[ -n "$SOCAT_PID" ]]; then
   
    # best case: process group kill
    kill -- -"$SOCAT_PID" 2>/dev/null || true

    # fallback
    kill "$SOCAT_PID" 2>/dev/null || true
  
  else
    echo "No active Mocktail server process found to stop." >&2
  fi

  echo "Mocktail server stopped." >&2

}

acquireScriptDependencies() {


  echo "Checking for required dependencies..." >&2

  # check if socat is installed, which is required for the server to function.
  if ! command -v socat &> /dev/null; then
    echo "Error: socat is not installed and is required for the Mocktail server to function, installing socat..." >&2
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
      sudo apt-get update && sudo apt-get install -y socat
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      brew install socat
    else
      echo "Unsupported OS type: $OSTYPE. Please install socat manually." >&2
      exit 1
    fi
  else
    echo "socat is already installed." >&2
  fi


  # check if JQ is installed, which is required for the server to function.
  if ! command -v jq &> /dev/null; then
    echo "Error: jq is not installed and is required for the Mocktail server to function, installing jq..." >&2
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
      sudo apt-get update && sudo apt-get install -y jq
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      brew install jq
    else
      echo "Unsupported OS type: $OSTYPE. Please install jq manually." >&2
      exit 1
    fi
  else
    echo "jq is already installed." >&2
  fi


  echo "All dependencies are satisfied." >&2
}

# configures server settings based on the main JSON system configuration file, setting global variables accordingly.
configureServer() {
  echo "Configuring Mocktail server..." >&2

  # check if the configuration file exists, if not create a default one.
  if [[ ! -f "$SCRIPT_DIR/res/config.json" ]]; then
    echo "Configuration file not found at $SCRIPT_DIR/res/config.json, creating a default configuration file..." >&2

    # create the config file.
    createDefaultConfigFile

    # pause for a breif moment to allow file to be written to the file system before we attempt to read it.
    sleep 1
  fi

 

  # read the configuration from the JSON file and set the global variables accordingly.
  local config_json
  config_json=$(ReadServerJSONConfig ".") || exit 1

  MAX_PROCESSES=$(ParseJSONConfigGeneralSetting "$config_json" "MaxConcurrentProcesses") || exit 1
  MAX_PROCESS_RUNTIME=$(ParseJSONConfigGeneralSetting "$config_json" "MaxHandlerProcessRuntime") || exit 1
  LISTEN_PORT=$(ParseJSONConfigGeneralSetting "$config_json" "ListeningPort") || exit 1
  AUTH_TOKEN_COOKIE_NAME=$(ParseJSONConfigSecuritySetting "$config_json" "AuthTokenCookieName") || exit 1
  AUTH_TOKEN_EXPIRATION_MINUTES=$(ParseJSONConfigSecuritySetting "$config_json" "TokenExpirationMinutes") || exit 1
  ADMIN_USER_EMAIL=$(ParseJSONConfigSecuritySetting "$config_json" "Email") || exit 1
  echo "Mocktail server configured with MaxProcesses=$MAX_PROCESSES, MaxProcessRuntime=$MAX_PROCESS_RUNTIME, ListenPort=$LISTEN_PORT, AuthTokenExpirationMinutes=$AUTH_TOKEN_EXPIRATION_MINUTES" >&2
}


initialiseBashletEngine() {
  echo "Mocktail: Initialising Bashlet Engine..." >&2
  # call into the BashletEngine script to initialise it, which will resolve any bashlet routes defined in the route configs.
  source "${SCRIPT_DIR}/res/bashlets/internal/BashletEngine"
  InitBashletEngine
}


exportSharedVariables() {
  export SCRIPT_DIR
  export MAX_PROCESSES
  export LISTEN_PORT
  export AUTH_TOKEN_COOKIE_NAME
  export AUTH_TOKEN_EXPIRATION_MINUTES
  export ADMIN_USER_EMAIL
  export PROCESS_USAGE_HISTORY_STATS_MMAP_FILE
  export BASHLET_CONTEXT_KV_STORE_MMAP_FILE
  
  local server_start_timestamp
  server_start_timestamp="$(date +%s)"
  export SERVER_START_TIMESTAMP="$server_start_timestamp"
}


# called to create a default configuration file at res/config.json if it does not already exist,
# for example if it was deleted in error or otherwise removed from the host file system.
createDefaultConfigFile(){

  cat > "$SCRIPT_DIR/res/config.json" <<EOL
{
  "Name": "Mocktail System Configuration",
  "Description": "Defines various Mocktail Server configuration properties and settings.",
  "Version": "1.0",
  "GeneralSettings": {
      "ListeningPort": 3333,
      "MaxConcurrentProcesses": 55,
      "MaxHandlerProcessRuntime": 11
  },
  "SecuritySettings": {
      "Email": "",
      "Passphrase": "",
      "AuthenticationMethod": "passphrase-and-token",
      "AuthTokenCookieName": "mocktail_auth_token",
      "TokenExpirationMinutes": 60,
      "EnableCORS": false,
      "AllowedOrigins": ["*"]
  }

}
EOL

  echo "Default configuration file created at $SCRIPT_DIR/res/config.json" >&2
}

# Gets the current count of running server processes.
getServerProcessCount() {
  current_processes=$(pgrep -fc "root-handler")
  echo "$current_processes"
}

# scheduled to run periodically (in a background process) to monitor the number of active processes across all Mocktail handlers, 
# and update a JSON file with the current process count for each minute of the last hour.
monitorProcessUsage() {

    #local historyFile="$SCRIPT_DIR/res/.process_usage_history.json"
    #local tmpFile="${historyFile}.tmp"
    #local historyFile="/dev/shm/process_usage_history.json"
    local historyFile="$PROCESS_USAGE_HISTORY_STATS_MMAP_FILE"
    local tmpFile="${historyFile}.tmp"
    

    jq -n '[range(60) | 0]' > "$historyFile"

    while true; do
        local minute currentProcessCount existing

        # get the current minute (0-59) to use as the index in the JSON array.
        minute=$(date '+%M')
        minute=$((10#$minute))

        # if the current minute is 0, reset the JSON file to start a new hour of tracking.
        if [[ "$minute" -eq 0 ]]; then
            jq -n '[range(60) | 0]' > "$historyFile"
        fi

        # if data values exists for values greater than the current minute, reset those values to 0 
        # to ensure we only track the last hour of data. This could happen if the machine was suspended or t
        # he script was paused for some reason, and then resumed after a period of time.
        nextMinute=$((minute + 1))
        nextValue=$(jq -r ".[$nextMinute]" "$historyFile")
        if [[ "$nextValue" -ne 0 ]]; then
            for ((i=nextMinute; i<60; i++)); do
                jq --argjson index "$i" '.[$index] = 0' "$historyFile" > "$tmpFile" && mv "$tmpFile" "$historyFile"
            done
        fi


        # get the current process count across all Mocktail handlers.
        currentProcessCount=$(getServerProcessCount)

        # get the existing value for the current minute from the JSON file.
        existing=$(jq -r ".[$minute]" "$historyFile")

        # compute max(current, existing) and only update the JSON file if the current process count 
        # is greater than the existing value for that minute.
        if (( currentProcessCount > existing )); then
            jq \
                --argjson minute "$minute" \
                --argjson value "$currentProcessCount" \
                '.[$minute] = $value' \
                "$historyFile" > "$tmpFile" &&
                mv "$tmpFile" "$historyFile"
        fi

        sleep 2
    done
}

# starts the process usage monitor function in the background, which will track the number of active processes over time and update a JSON file
# with the current process count for each minute of the last hour.
startProcessUsageMonitor() {
    echo "Starting process usage monitor in background..." >&2
    monitorProcessUsage &
    PROCESS_MONITOR_PID=$!
    echo "Process usage monitor started in background with PID: $PROCESS_MONITOR_PID" >&2
}

stopProcessUsageMonitor() {
   echo "Stopping process usage monitor..." >&2
   if [[ -n "$PROCESS_MONITOR_PID" ]]; then
        echo "Stopping process usage monitor (PID: $PROCESS_MONITOR_PID)..." >&2
        kill "$PROCESS_MONITOR_PID" 2>/dev/null || true
        wait "$PROCESS_MONITOR_PID" 2>/dev/null || true
        PROCESS_MONITOR_PID=""
        echo "Process usage monitor stopped." >&2
    else
        echo "No active process usage monitor found to stop." >&2
    fi
    echo "Process usage monitor stopped." >&2
}

clearMMAPFiles() {
    echo "Clearing memory-mapped files..." >&2
    rm -f "$PROCESS_USAGE_HISTORY_STATS_MMAP_FILE" "$BASHLET_CONTEXT_KV_STORE_MMAP_FILE"
    echo "Memory-mapped files cleared." >&2
}

# we iterate over all sub directories from the root script directory and assign any script files found 
# as a result, execution permissions via chmod +x to ensure they can be executed by the server when needed.
# as the script files are NOT suffixed with .sh or .bash, we cannot rely on the file extension to determine 
# if they are executable scripts, thus we must read the first line of each file to check for the shebang (#!) 
# which indicates it is a script file.
applySubScriptFilePermissions() {
    echo "Applying file permissions..." >&2

    find "$SCRIPT_DIR/res" -type f -exec bash -c '
        for file; do
            if head -n 1 "$file" | grep -q "^#!"; then
                chmod +x "$file"

            fi
        done
    ' bash {} + 
   
    echo "File permissions applied." >&2
}


# apply readonly permissions to any files in the internal directory, i.e we remove write permissions.
# here we check if the path contains internal and apply the permissions accordingly.
applyInternalFilePermissions() {
    echo "Applying readonly permissions to internal files..." >&2

    find "$SCRIPT_DIR/res" -type f -path "*/internal/*" -exec chmod a-w {} +

    echo "Readonly permissions applied to internal files." >&2
}


# apply readonly permissions to any files in the system directory, i.e we remove write permissions.
applySystemFilePermissions() {
  
    echo "Applying readonly permissions to system files..." >&2

    find "$SCRIPT_DIR/res" -type f -path "*/sys/*" -exec chmod a-w {} +

    echo "Readonly permissions applied to system files." >&2
}


applyServerFilePermissions(){
  
    echo "Applying file permissions to server files..." >&2

    applySubScriptFilePermissions
    applyInternalFilePermissions
    applySystemFilePermissions

    echo "File permissions applied to server files." >&2
}



# call script entry point.
startup

