#!/bin/bash

#-----------------------------------------------------------------------------------------------------------------
# Name: user-handler (mocktail)
# Author Giles Thompson
# Date:  08/06/2026
# Description: This handler is responsible for handling user defined routes under the base path "/usr"
#              It is invoked by the root-handler when a request matches the "/usr" path prefix and will
#              attempt to map the path provided in the request to a specifc user-defined API endpoint.
#              
#
# IMPORTANT: IT GENERALLY SHOULD NOT BE NECESSARY TO MODIFY THIS FILE, and it's recommended that one does not
#            unless they know what they are doing and have a specific reason to do so. The handler is one
#            of two default handlers defined by the Mocktail Server and is used to route requests to user-defined 
#            bashlets, under the default "/usr" path prefix.
#-----------------------------------------------------------------------------------------------------------------



# import the handler utility functions, which are used by this handler to perform common tasks such as route resolution and response generation.
source "${SCRIPT_DIR}/res/handlers/internal/utils/handler-utils"

# vars passed into us from our parent root-handler
FULL_PATH="$1"
METHOD="$2"
PROTOCOL="$3"
RELATIVE_PATH="$4"
REQUEST_JSON_OBJECT="$5"


handleRequest(){

  echo "user-handler: Received a request associated with (relative) path '$RELATIVE_PATH', processing..." >&2

   # issue a call into our utility method to attempt to resolve route for the (relative) path 
   # provided to us by the root handler, which will have stripped the base path associated with 
   # this handler (i.e "/sys") from the original request path, we also taking care to pass in 
   # the path to THIS handlers routes config
   local config_path="${SCRIPT_DIR}/res/handlers/usr/user-handler-routes.json"
   route_info=$(ResolveRouteFromPath "$RELATIVE_PATH" "$config_path")

   # where we have found a matching route, call into our utility function to handle the request 
   # according to it declared route type, otherwise dispatch an appropriate error response.
   if [[ -n "$route_info" ]]; then
       HandleRequestAccordingToRoute "$route_info" "$RELATIVE_PATH" "$METHOD" "$PROTOCOL" "$REQUEST_JSON_OBJECT"
   else
     DispatchErrorResponse 404 "The requested resource was not found" "application/json" "$FULL_PATH" "$METHOD" "$REQUEST_JSON_OBJECT"
   fi
  
}

handleRequest