#!/bin/bash

# import the handler utility functions, which are used by this handler to perform common tasks such as route resolution and response generation.
source "$(dirname "${BASH_SOURCE[0]}")/../../utils/handler-utils"


# top-level request handler function which will delegate to other sub handlers, as necessary, to process the incoming
# request and return an appropriate response to the  client. We only expect sub handler route types to
# be defined in the root-handler's configuration, as this is the entry point for all requests. The only
# exception will be one or more wildcard static routes for serving static respources such as HTML files,CSS, JS etc,
# which may be directly referenced in .html file served by the system handler, 
handleRequest(){

   echo "root-handler: Received a request, processing..." >&2
  
   # check the handling of this request will not cause us to exceed the maximum process limit.
   checkProcessLimit
  
   # read and parse the incoming request to a high-level JSON object.
   requestJSON=$(ReadAndParseRequest) || exit 1

   # call into helpers to parse method, path and protocol from the request (line)
   method=$(parseRequestMethod "$requestJSON")
   path=$(parseRequestPath "$requestJSON")
   protocol=$(parseRequestProtocol "$requestJSON")

   # issue a call into our utility method to attempt to resolve route for the path parsed from the request
   # taking care ton pass in the path to THIS handlers routes config
   local config_path="${SCRIPT_DIR}/res/handlers/internal/root-handler-routes.json"
   route_info=$(ResolveRouteFromPath "$path" "$config_path")

    # where we have found a matching route, call into our utility function to handle the request 
    # according to it declared route type, otherwise dispatch an appropriate error response.
    if [[ -n "$route_info" ]]; then
        HandleRequestAccordingToRoute "$route_info" "$path" "$method" "$protocol" "$requestJSON"
    else
      DispatchErrorResponse 404  "$path" "$method" "$protocol"
    fi

}


# unique to this top-level root handler, checks that the current number of active processes
# across all Mocktail handlers has not exceeded the predefined maximum as defined in
# the preveiling config, where this IS the case the the call to this handler will immediately
# return an appropriate error response will be dispatched to the caller.
checkProcessLimit() {
  if [[ -n "$MAX_PROCESSES" ]]; then
    current_processes=$(pgrep -fc "root-handler")
    echo "root-handler: Current processes: $current_processes" >&2
    if (( current_processes > MAX_PROCESSES )); then
      echo "root-handler: Maximum process limit reached ($current_processes), refusing connection." >&2
      exit 1
    fi
  fi
}


# call top-level entry point function.
handleRequest
