#!/bin/bash

# import the handler utility functions, which are used by this handler to perform common tasks such as route resolution and response generation.
source "${SCRIPT_DIR}/res/handlers/internal/utils/handler-utils"


# PUBLIC FUNCTION: DelegateRequest, similar to the handleRequest function, the principal difference is handlerRequest is 
# invoked when an external request is received to the Mocktail server, from a remote client. Conversely DelegateRequest enables
# other internal handlers to invoke this root handler to process a request on their behalf. On recceipt of the
# request the root handler will parse and route the request to the appropriate sub handler in a similar manner to how handleRequest 
# processes request received over the wire. However as the request is NOT received over the wire, no attempt will be made
# to read the request data from stdin, instead, the call to this function requires that all pertinent request information be provided as arguments.
DelegateRequest(){
  
    # capture the request information passed in as arguments to this function.
    delegate_req_path="$1"
    delegate_req_method="$2"
    delegate_req_protocol="$3"
    delegate_req_json="$4"

    # issue a call into our utility method to attempt to resolve route for the path parsed from the request
    # taking care ton pass in the path to THIS handlers routes config
    local config_path="${SCRIPT_DIR}/res/handlers/internal/root-handler-routes.json"
    route_info=$(ResolveRouteFromPath "$delegate_req_path" "$config_path")

    # where we have found a matching route, call into our utility function to handle the request 
    # according to it declared route type, otherwise dispatch an appropriate error response.
    if [[ -n "$route_info" ]]; then
        HandleRequestAccordingToRoute "$route_info" "$delegate_req_path" "$delegate_req_method" "$delegate_req_protocol" "$delegate_req_json"
    else
      DispatchErrorResponse 404 "The requested resource was not found" "application/json" "$delegate_req_path" "$delegate_req_method" "$delegate_req_json"
    fi



}

# PUBLIC FUNCTION: GetCurrentServerProcessCount, returns the current number of active processes across all Mocktail handlers.
GetCurrentServerProcessCount() {
  current_processes=$(pgrep -fc "root-handler")
  echo "$current_processes"
}


# default, top-level request handler function which will delegate to other sub handlers, as necessary, to process the incoming
# request and return an appropriate response to the  client. We only expect sub handler route types to
# be defined in the root-handler's configuration, as this is the entry point for all requests. The only
# exception will be one or more wildcard static routes for serving static respources such as HTML files,CSS, JS etc,
# which may be directly referenced in .html file served by the system handler, 
handleRequest(){

   #echo "root-handler: Received a request, processing..." >&2
   Log "INFO" "Root handler received a request, processing..."

  
   # check the handling of this request will not cause us to exceed the maximum process limit.
   checkProcessLimit
  
   # read and parse the incoming request to a high-level JSON object.
   requestJSON=$(ReadAndParseRequest) || exit 1

   # call into helpers to parse method, path and protocol from the request (line)
   method=$(parseRequestMethod "$requestJSON")
   path=$(parseRequestPath "$requestJSON")
   protocol=$(parseRequestProtocol "$requestJSON")


   # if the request method is OPTIONS, we will respond with a 200 OK and the appropriate CORS headers, as this is a pre-flight request
   # and is handled at the server level, without the need to route to a specific handler. Support for OPTIONS at the application level
   # will br added in later releases.
   if [[ "$method" == "OPTIONS" ]]; then
       Log "INFO" "root-handler: Received an OPTIONS request, responding with 200 OK and CORS headers..."
       DispatchOptionsResponse "$path" "$method" "$requestJSON"
       return 0
   fi



   # issue a call into our utility method to attempt to resolve route for the path parsed from the request
   # taking care ton pass in the path to THIS handlers routes config
   local config_path="${SCRIPT_DIR}/res/handlers/internal/root-handler-routes.json"
   route_info=$(ResolveRouteFromPath "$path" "$config_path")

    # where we have found a matching route, call into our utility function to handle the request 
    # according to it declared route type, otherwise dispatch an appropriate error response.
    if [[ -n "$route_info" ]]; then
        HandleRequestAccordingToRoute "$route_info" "$path" "$method" "$protocol" "$requestJSON"
    else
      DispatchErrorResponse 404 "The requested resource was not found" "application/json" "$path" "$method" "$requestJSON"
    fi

}


# unique to this top-level root handler, checks that the current number of active processes
# across all Mocktail handlers has not exceeded the predefined maximum as defined in
# the preveiling config, where this IS the case the the call to this handler will immediately
# return an appropriate error response will be dispatched to the caller.
checkProcessLimit() {
    if [[ -n "$MAX_PROCESSES" ]]; then
    current_server_processes=$(GetCurrentServerProcessCount)
    Log "INFO" "root-handler: Current processes: $current_server_processes"
    if (( current_server_processes > MAX_PROCESSES )); then
      Log "ERROR" "root-handler: Maximum process limit reached ($current_server_processes), refusing connection."
      DispatchErrorResponse 429 "Max concurrent request limit reached" "application/json" "$path" "$method" "$requestJSON" 
      exit 1
    fi
  fi
}






# export the DelegateRequest function.
export -f DelegateRequest

# export the GetCurrentServerProcessCount function.
export -f GetCurrentServerProcessCount


# call top-level entry point function, unless this handler is being invoked as a result of a DelegateRequest from another handler,
# as indicated by the presence of a non-empty REQUEST_JSON_OBJECT. The REQUEST_JSON_OBJECT would have been set by the initial handler that 
# invoked this handler via the DelegateRequest function.
if [[ -z "$REQUEST_JSON_OBJECT" ]]; then
  handleRequest
fi
