#!/bin/bash


#A suite of handler utility functions, used by all handler scripts, to perform common tasks 
# such as request parsing, route resolution and response generation/return.

# log messsag to indicate that the script has been successfully loaded/sourced
echo "handler-utils: Loaded handler utility functions." >&2

# import/source the mime type utility functions, which are used by the static route handling logic to determine the correct content type to return for static resources.
source "${SCRIPT_DIR}/res/handlers/internal/utils/mime-utils" #we use path relative to this script, the utilities both share the same parent "utils" directory.


# import/source the BashletEngine so we can delegate to it for handling requests associated with Bashlet route types.
source "${SCRIPT_DIR}/res/bashlets/internal/BashletEngine" #we use path relative to this script, the BashletEngine is located in the "

# PUBLIC FUNCTION: reads and parses the request read from the socket into an array of headers and a body, taking care to handle the case where the 
# request may not have a body, and return the headers and body as separate variables.
ReadAndParseRequest(){ 

  local method path protocol
  local header
  local content_length=0
  local headers='{}'
  local body=''
  local query_raw
  local query_json='{}'
  local content_type #we store this as we may to do additional parsing of the body based on this value. e.g where its: "application/x-www-form-urlencoded" 
  local form_data_json='{}'
  local cookies_raw=''
  local cookies_json='{}'

  read -r -t 5 method path protocol || return 1

  # Extract the query string from the path (safe split)
  if [[ "$path" == *\?* ]]; then
    query_raw="${path#*\?}"
    path="${path%%\?*}"
  else
    query_raw=""
  fi

  echo "handler-utils: Received request>>>>: $method $path $protocol " >&2
  #echo "QUERY STRING IS: $query_string" >&2

  # parse headers into json objects of key value pairs, taking care to handle the case where the request may not have any headers, and return the headers as a json object.
  while IFS= read -r header; do
  
      header=${header%$'\r'} 
      [[ -z "$header" ]] && break 
      local name=${header%%:*}
      local value=${header#*: }

      # if the current header is "Content-Type" we store it in a variable for later use, 
      # as we may need to do additional parsing of the body based on this value. e.g where its: "application/x-www-form-urlencoded" 
      [[ $name == "Content-Type" ]] && content_type=$value

      # if the current header is "Cookie" we store it in a variable for later use, as we may need to do additional parsing of 
      # the cookies name value pairs  e.g where its: "session_id=abc123; path=/; secure; HttpOnly; SameSite=Strict"
      [[ $name == "Cookie" ]] && cookies_raw=$value

      headers=$(
          jq \
              --arg name "$name" \
              --arg value "$value" \
              '. + {($name): $value}' \
              <<< "$headers"
      ) 
      [[ $name == "Content-Length" ]] &&
          content_length=$value
  done

  if (( content_length > 0 )); then
      IFS= read -r -N "$content_length" body
  fi

  
  # similarly parse query string into json objects of key value pairs, taking care to handle the case where the request may not have any query parameters, and return the query string as a json object.
    if [[ -n "$query_raw" ]]; then
      IFS='&' read -ra query_params <<< "$query_raw"
      for param in "${query_params[@]}"; do
        local name=${param%%=*}
        local value=${param#*=}
        query_json=$(
          jq \
            --arg name "$name" \
            --arg value "$value" \
            '. + {($name): $value}' \
            <<< "$query_json"
        )
      done
    fi

  # if the request content-type header is equal to: "application/x-www-form-urlencoded" then the
  # body of the request will be a series of name-value pairs separated by the "&" character, 
  # we will parse these into a json object of key value pairs, taking care to handle the case where the request may not have any body parameters.
  if [[ "$content_type" == "application/x-www-form-urlencoded" && -n "$body" ]]; then
      IFS='&' read -ra body_params <<< "$body"
      local body_json='{}'
      for param in "${body_params[@]}"; do
        local name=${param%%=*}
        local value=${param#*=}
        body_json=$(
          jq \
            --arg name "$name" \
            --arg value "$(urlDecode "$value")" \
            '. + {($name): $value}' \
            <<< "$body_json"
        )
      done
      form_data_json="$body_json"
  fi

  #  next if one or more cookies have been provided in the request we parse each one into a json object of key value pairs, taking care to 
  # handle the case where the request may not have any cookies, and return the cookies as a json object.
  if [[ -n "$cookies_raw" ]]; then
      IFS=';' read -ra cookie_params <<< "$cookies_raw"
      for cookie in "${cookie_params[@]}"; do
        cookie="${cookie#${cookie%%[![:space:]]*}}"
        cookie="${cookie%${cookie##*[![:space:]]}}"
        [[ -z "$cookie" ]] && continue

        local name=${cookie%%=*}
        local value=${cookie#*=}

        cookies_json=$(
          jq \
            --arg name "$name" \
            --arg value "$value" \
            '. + {($name): $value}' \
            <<< "$cookies_json"
        )
      done
  fi

  jq -n \
      --arg method "$method" \
      --arg path "$path" \
      --arg protocol "$protocol" \
      --arg body "$body" \
      --argjson headers "$headers" \
      --argjson query_string "$query_json" \
      --argjson form_data "$form_data_json" \
      --argjson cookies "$cookies_json" \
      '{
          method: $method,
          path: $path,
          protocol: $protocol,
          headers: $headers,
          query_string: $query_string,
          body: $body,
          form_data: $form_data,
          cookies: $cookies
      }'

}

 

# PUBLIC FUNCTION: attempts to resolve the defined route associated with the specified path 
ResolveRouteFromPath() {

 local path="$1"
 local config_path="$2"
 local route_info

 echo "handler-utils: Resolving route for path: $path using configuration standby..." >&2

 # Use jq to select the longest matching wildcard route, then extract the
 # route type and handler script for sub-handler routes.
 route_info="$({
    jq -c --arg path "$path" '
      [.Routes[]
       | .Path as $route_path
       | select(
           ($route_path | rtrimstr("*") | rtrimstr("/")) as $prefix
           | (
               ($path == $prefix)
               or ($path | startswith($prefix + "/"))
               or ($path | startswith($prefix + "?"))
             )
         )
      ]
      | sort_by(.Path | length)
      | reverse
      | .[0] // empty
    ' "${config_path}"
  })"

 # where we have found a matching route return it.
 if [[ -n "$route_info" ]]; then
     echo "handler-utils: Successfully resolved route for path: $path" >&2
     echo "$route_info"
  else
        echo "handler-utils: No matching route found for path: $path" >&2
        echo "" # return empty string to indicate no route found 
 fi
   

}

# PUBLIC FUNCTION: handles the request according to the route Type defined in the route data provided as the first 
# parameter to this function. Where the specified route type is unsupported an appropriate error
# response will be generated and returned to the client.
HandleRequestAccordingToRoute() {
  echo "handler-utils: Handling request for path: $path according to resolved route..." >&2
  local route_info="$1"
  local path="$2"
  local method="$3"
  local protocol="$4"
  local request_json_object="$5"

  #parse the route type from the route info, then handle request according to it.
  route_type=$(parseRouteType "$route_info")
  case "$route_type" in
    "sub-handler")
        handleSubHandlerRouteRequest "$route_info" "$path" "$method" "$protocol" "$request_json_object"
        ;;
    "static")
        handleStaticRouteRequest "$route_info" "$path" "$method" "$protocol" "$request_json_object"
        ;;
    "bashlet")
        handleBashletRouteRequest "$route_info" "$path" "$method" "$protocol" "$request_json_object"
        ;;
    *)
        echo "root-handler: Unsupported route type: $route_type for path: $path, sending error response." >&2
        DispatchErrorResponse 500 "Unsupported route type: $route_type for path: $path" "application/json" "$path" "$method" "$request_json_object"
        echo "root-handler: Default response sent for path: $path, closing connection." >&2
        ;;
  esac

}


DispatchResponse(){

    local statusCode="$1"
    local content="$2"
    local contentType="$3"

    printf "HTTP/1.1 %s %s\r\n" "$statusCode" "$(StatusMsgForCode "$statusCode")"
    printf "Content-Type: %s\r\n" "$contentType"
    printf "Content-Length: %s\r\n" "${#content}"
    printf "Connection: close\r\n"
    printf "\r\n"
    printf "%s" "$content"

}

DispatchRedirectResponse() {
    local redirect_url="$1"
    local status_code=302
    local status_message="$(GetStatusMsgForCode $status_code)"
    local headers="{\"Location\": \"$redirect_url\"}"
    local content_type="text/html"
    local content="<html><body><p>$status_code $status_message</p><p>Redirecting to <a href=\"$redirect_url\">$redirect_url</a></p></body></html>"

    printf "HTTP/1.1 %s %s\r\n" "$status_code" "$status_message"
    printf "Content-Type: %s\r\n" "$content_type"
    printf "Content-Length: %s\r\n" "${#content}"
    printf "Connection: close\r\n"
    printf "Location: %s\r\n" "$redirect_url"
    printf "\r\n"
    printf "%s" "$content"
}


# PUBLIC FUNCTION: dispatches an error response to the client based on the provided error code, path, method and protocol. 
# The response will include a JSON body with details of the error.
DispatchErrorResponse(){

   local statusCode="$1"
   local content="$2"
   local contentType="$3"
   local path="$4"
   local method="$5"
   local fullRequestObject="$6"

    local statusMessage="$(GetStatusMsgForCode $statusCode)"
   
  
   # esnure that the status code begins with a 4 or 5 to indicate a client or server error respectively, 
   # if not we default to a 500 internal server error.
    if [[ ! "$statusCode" =~ ^[45] ]]; then
        echo "handler-utils: Invalid error status code: $statusCode, defaulting to 500 Internal Server Error." >&2
        statusCode=500
        content="Internal Server Error - An invalid error status code was provided. The path was: $path. The  method was: $method. The original error status code was: $1. The original error content was: $content"
    fi

   # if the client that initated the request accepts HTML, we will return an HTML error page, otherwise we will return a JSON error response.
   if reqAcceptsHtml "$fullRequestObject"; then
       DispatchRedirectResponse "/sys/ui/errors-dynamic.html?status=$statusCode&message=$statusMessage&content=$content | Request Path: $path Request Method: $method"
   else
       # delegate to the default dispatch response function.
       body='{"status":"'"$statusMessage"'","method":"'"$method"'","path":"'"$path"'","details":"'"$content"'"}'
       DispatchResponse "$statusCode" "$body" "$contentType"
   fi


}

# Genertes a SHA-512 hash of the provided input string and returns the hash value.
ToSha512() {
    local input="$1"
    echo -n "$input" | sha512sum
}


ComputePassphrase() {
    local email="$1"
    local password="$2"
    local passphrase
    passphrase="$(ToSha512 "$email-$password")"
    echo "$passphrase"
}


#-------------------------------- PRIVATE HELPER/UTILITY FUNCTION IMPLEMENTATIONS ---------------------------------


# handles SubHandler type route requests by delgating to the specified sub-handler script defined in the route info, 
# where the route type is unsupported or no valid script is provided an appropriate error response will be generated 
# and returned to the client.
handleSubHandlerRouteRequest() {
  echo "handler-utils: Handling request for path: $path according to SubHandler route type..." >&2
  local route_info="$1"
  local request_path="$2"
  local request_method="$3"
  local request_protocol="$4"
  local request_json_object="$5"

  local route_type=$(parseRouteType "$route_info")
  local route_path=$(parseRoutePath "$route_info")
  local route_sub_handler_script="$(parseSubHandlerRouteScript "$route_info")"

  # ensure the route type is of type sub handler and a sub handler script path has been specified.
  if [[ "$route_type" == "sub-handler" && -n "$route_sub_handler_script" ]]; then
    route_sub_handler_script="${route_sub_handler_script#/}"  # parse the relative sub-handler script path from the config, ensuring we remove any leading slash to avoid issues when constructing the full path.
    route_sub_handler_script="${SCRIPT_DIR}/${route_sub_handler_script}" # construct the full path to the sub-handler script by combining the basescript directory path with the relative path from the config.
    echo "root-handler: Routing to sub-handler script: $route_sub_handler_script for path: $request_path" >&2
    
    # before delegating to the sub-handler script we need to strip the matched prefix from the path, this is because the sub-handlers will 
    # expect paths to be relative to their own defined route path, for example if we have a route with the path "/usr" and a request comes in 
    # for "/usr/profile", when we delegate to the sub-handler we want to pass it "profile" as the path rather than "/usr/profile", 
    # this allows the sub-handler to be more flexible and reusable as it can be mounted at different base paths without needing to 
    # worry about adjusting the paths it receives.
    local stripped_request_path=$(stripPrefixFromPath "$request_path" "$route_path")
    "$route_sub_handler_script" "$request_path" "$request_method" "$request_protocol" "/$stripped_request_path" "$request_json_object"
    return $?
  else
    echo "handler-utils: Unsupported route type: $route_type or script definition for SubHandler route type associated with path: $request_path, sending default response." >&2
    DispatchErrorResponse 500 "Unsupported route type: $route_type for path: $request_path" "application/json" "$request_path" "$request_method" "$request_json_object"
  fi
}



# handles Static type route requests by reading the specified static resource from the file system and 
#returning its contents in the response body, where the route type is unsupported or no valid file path is provided 
#an appropriate error response will be generated and returned to the client.
handleStaticRouteRequest() {
  echo "handler-utils: Handling request for path: $path according to Static route type..." >&2

  # for static routes we will have a path to a static resource i.e. file, defined in the config
  # we parse those details here then attempt to read the file into memory and return its contents
  # in the response body, we also set the content type based on the file extension, defaulting to 
  # application/json if we cannot determine a specific type.
  local route_info="$1"
  local request_path="$2"
  local request_method="$3"
  local request_protocol="$4"
  local request_json_object="$5"



  local route_path=$(parseRoutePath "$route_info")
  local route_type=$(parseRouteType "$route_info")
  local route_file_path="$(parseStaticRouteFilePath "$route_info")"
  if [[ "$route_type" == "static" && -n "$route_file_path" ]]; then 
    
    # echo "&&&********* Called by: ${BASH_SOURCE[2]}" >&2
    # what we do next will depend on whether this is a wildcard static route or not as denoted
    # by a route Path that is suffixed with a wildcard i.e "*" character
    absolute_file_path=""
    if [[ "$route_path" == *"*" ]]; then
     
        echo "handler-utils: Handling request for wildcard static route, stripping wildcard character AND trailing slash (if it exists) from route path..." >&2
        
        # we need to strip the wildcard character from the end of the route path, we also want to ensure we strip any trailing slash that may be left after removing 
        # the wildcard character as this will interfere with our path resolution logic later on.
        route_path="${route_path%\*}" 
        route_path="${route_path%/}"

        # build up the absolute file path by stripping the route prefix from the
        # request path and joining that remainder with the configured FilePath.
        # e.g. route Path: /assets/*, request_path: /assets/modules/x.css
        # remainder => modules/x.css, final => [SCRIPT_DIR]/[FilePath]/modules/x.css
        local stripped_request_path
        stripped_request_path=$(stripPrefixFromPath "$request_path" "$route_path")

        # Use realpath -m to normalize duplicate slashes and path segments
        if command -v realpath >/dev/null 2>&1; then
          absolute_file_path=$(realpath -m "${SCRIPT_DIR}/${route_file_path#/}/${stripped_request_path#/}")
        else
          # Fallback: manually strip trailing slash from base and join
          base="${route_file_path#/}"
          base="${base%/}"
          if [[ -n "$stripped_request_path" ]]; then
            absolute_file_path="${SCRIPT_DIR}/${base}/${stripped_request_path#/}"
          else
            absolute_file_path="${SCRIPT_DIR}/${base}"
          fi
        fi
        echo "handler-utils: final file path for static (wildcard) route is: $absolute_file_path" >&2

    else
      echo "handler-utils: Handling request for non-wildcard static route..." >&2  
      # build up absilute path to the file by concatenting the base script directory with the file path defined in the config for this route, this will allow us to correctly resolve the file on disk that corresponds to the request.
      absolute_file_path="${SCRIPT_DIR}/${route_file_path#/}"
      echo "handler-utils: final file path for static route is: $absolute_file_path" >&2
    fi


    # next, irrespective of how we derive the path to file, we validate that the final file path exists on the system before proceeding.
    if [[ -f "$absolute_file_path" ]]; then
      echo "handler-utils: Successfully found static resource for path: $path at file path: $route_file_path" >&2

      # Determine MIME type from filename and stream the file to the client
      local content_type
      content_type=$(getMimeType "$absolute_file_path")
      dispatchFileResponse "$absolute_file_path" "$content_type"

    echo "handler-utils: Static resource response sent for path: $path, closing connection." >&2
    elif [[ -d "$absolute_file_path" ]]; then
      
      #echo "absolute_file_path: $absolute_file_path, script file path: $SCRIPT_DIR" >> log.txt

      echo "handler-utils: Static resource path is a directory for path: $path at file path: $route_file_path, looking for default index file..." >&2
      # Check if there's an index.html file in the directory
      if [[ -f "$absolute_file_path/index.html" ]]; then
        dispatchFileResponse "$absolute_file_path/index.html" "text/html"
        echo "handler-utils: Static resource response sent for path: $path, found index.html, closing connection." >&2
      #final check: if the provided path is the server www root and no index.html exist we return the default mocktail welcome page to the client.
      elif [[ "$absolute_file_path" == "/home/gilesthompson/erudite/shareful-oss/shareful-utils-mocktail/res/usr/www" ]]; then
        dispatchFileResponse "${SCRIPT_DIR}/res/handlers/internal/xmocktail-welcome-page.html" "text/html"
        echo "handler-utils: Static resource response sent for path: $path, found index.htm, closing connection." >&2
      else
        DispatchErrorResponse 404 "The provided path references a directory that DOES NOT contain an index.html file" "application/json" "$request_path" "$request_method" "$request_json_object"
      fi
    else
      echo "handler-utils: Static resource file not found for path: $path at file path: $route_file_path, the absolute file path was: $absolute_file_path, sending error response." >&2
      DispatchErrorResponse 404 "The requested resource was not found" "application/json" "$request_path" "$request_method" "$request_json_object"
    fi
  else
    echo "handler-utils: Unsupported route type: $route_type or file path definition for Static route type associated with path: $path, sending error response." >&2
    DispatchErrorResponse 500 "Unsupported route type: $route_type or file path definition for Static route type associated with path: $path" "application/json" "$request_path" "$request_method" "$request_json_object"
  fi    
  
}

handleBashletRouteRequest() {
  echo "handler-utils: Handling request for path: $path according to Bashlet route type..." >&2
  local route_info="$1"
  local request_path="$2"
  local request_method="$3"
  local request_protocol="$4"
  local request_json_object="$5"


  local route_type=$(parseRouteType "$route_info")
  local route_path=$(parseRoutePath "$route_info")

  # ensure the route type is of type bashlet and a request object has been provided.
  if [[ "$route_type" == "bashlet" && -n "$request_json_object" ]]; then

    echo "handler-utils: Routing to Bashlet Engine for path: $request_path" >&2

    # delegate to the BashletEngine to handle the request, passing in the request object as a parameter.
    DelegateRequestToBashletEngine "$route_path" "$request_json_object" "$request_path"
  else
    echo "handler-utils: Unsupported route type: $route_type or missing request object for Bashlet route type associated with path: $request_path, sending error response." >&2
    DispatchErrorResponse 500 "Unsupported route type: $route_type for path: $request_path" "application/json" "$request_path" "$request_method" "$request_json_object"
  fi    

}

handleJsonResponseRouteRequest(){
    echo "handler-utils: Handling request for path: $path according to JsonResponse route type..." >&2
}





# dispatches an error response to the client based on the provided error code, path, method and protocol. 
# The response will include a JSON body with details of the error.
dispatchErrorResponse(){
   local statusCode="$1"
   local content="$2"
   local contentType="$3"
   local acceptsHtml="$4"

   # if the client accepts HTML, we will return an HTML error page, otherwise we will return a JSON error response.
    if [[ "$acceptsHtml" == "true" ]]; then
        local errorPageContent="<html><head><title>Error $statusCode</title></head><body><h1>Error $statusCode</h1><p>$content</p></body></html>"
        dispatchResponse "$statusCode" "$errorPageContent" "text/html"
    else
       DispatchResponse "$statusCode" "$content" "$contentType"
    fi

   

}

dispatchSuccessResponse(){
    local content="$1"
    local contentType="$2"
    
     printf "HTTP/1.1 200 OK\r\n"
     printf "Content-Type: %s\r\n" "$contentType"
     printf "Content-Length: %s\r\n" "${#content}"
     printf "Connection: close\r\n"
     printf "\r\n"
     printf "%s" "$content"
}




dispatchFileResponse(){
  local file_path="$1"
  local contentType="$2"

  # Prefer stat for size, fallback to wc -c
  local size
  if ! size=$(stat -c%s "$file_path" 2>/dev/null); then
    size=$(wc -c <"$file_path" 2>/dev/null || echo 0)
  fi

  printf "HTTP/1.1 200 OK\r\n"
  printf "Content-Type: %s\r\n" "$contentType"
  printf "Content-Length: %s\r\n" "$size"
  printf "Connection: close\r\n"
  printf "\r\n"
  cat "$file_path"

}


stripPrefixFromPath() {
    local path="$1"
    local prefix="$2"

    if [[ "$path" == "$prefix" ]]; then
        echo ""
    elif [[ "$path" == "$prefix"/* ]]; then
        echo "${path#"$prefix"/}"
    else
        echo "$path"
    fi
}


# provided with a URL encoded string, this function will decode it and return the resultant decoded string.
urlDecode() {
    local encoded="$1"
    local decoded
    decoded=$(printf '%b' "${encoded//%/\\x}")
    echo "$decoded"
}

# provided with a string, this function will URL encode it and return the resultant encoded string.
urlEncode(){
  local value="$1"
  local encoded
  encoded=$(jq -nr --arg v "$value" '$v|@uri')
  echo "$encoded"
}



#--------------------------------------- ROUTE PARSING METHODS -----------------------------


parseRouteTitle() {
  local route_info="$1"
  jq -r '.Title // empty' <<< "$route_info"
}

parseRoutePath() {
  local route_info="$1"
  jq -r '.Path // empty' <<< "$route_info"
}

parseRouteType() {
  local route_info="$1"
  jq -r '.Type // empty' <<< "$route_info"
}


parseSubHandlerRouteScript() {
  local route_info="$1"
  jq -r '.SubHandlerScript // empty' <<< "$route_info"
}

parseStaticRouteFilePath() {
  local route_info="$1"
  jq -r '.FilePath // empty' <<< "$route_info"
}

parseJsonResponseRoutePayload() {
  local route_info="$1"
  jq -r '.Payload // empty' <<< "$route_info"
}




#--------------------------------------- INBOUND REQUEST PARSING METHODS -----------------------------

parseRequestMethod() {
  local request="$1"
  jq -r '.method' <<< "$request"
}

parseRequestPath() {
  local request="$1"
  jq -r '.path' <<< "$request"
}

parseRequestProtocol() {
  local request="$1"
  jq -r '.protocol' <<< "$request"
}

parseRequestHeaders() {
  local request="$1"
  jq -r '.headers' <<< "$request"
}

parseRequestHeader() {
  local request="$1"
  local header_name="$2"
  jq -r --arg header_name "$header_name" '.headers[$header_name] // empty' <<< "$request"
}

parseRequestQueryString() {
  local request="$1"
  jq -r '.query_string' <<< "$request"
}


parseRequestQueryStringParam() {
  local request="$1"
  local parameter_name="$2"
  jq -r --arg parameter_name "$parameter_name" '.query_string[$parameter_name] // empty' <<< "$request"
}

parseRequestBody() {
  local request="$1"
  jq -r '.body' <<< "$request"
}

ParseFormData() {
  local request="$1"
  jq -r '.form_data' <<< "$request"
}

ParseFormDataParam() {
  local request="$1"
  local parameter_name="$2"
  jq -r --arg parameter_name "$parameter_name" '.form_data[$parameter_name] // empty' <<< "$request"
}

parseRequestCookies() {
  local request="$1"
  jq -r '.cookies' <<< "$request"
}

parseRequestCookiesParam() {
  local request="$1"
  local cookie_name="$2"
  jq -r --arg cookie_name "$cookie_name" '.cookies[$cookie_name] // empty' <<< "$request"
}

StatusMsgForCode() {

    local status_code="$1"

    case "$status_code" in
    100) printf "Continue" ;;
    101) printf "Switching Protocols" ;;
    102) printf "Processing" ;;
    103) printf "Early Hints" ;;

    200) printf "OK" ;;
    201) printf "Created" ;;
    202) printf "Accepted" ;;
    203) printf "Non-Authoritative Information" ;;
    204) printf "No Content" ;;
    205) printf "Reset Content" ;;
    206) printf "Partial Content" ;;
    207) printf "Multi-Status" ;;
    208) printf "Already Reported" ;;
    226) printf "IM Used" ;;

    300) printf "Multiple Choices" ;;
    301) printf "Moved Permanently" ;;
    302) printf "Found" ;;
    303) printf "See Other" ;;
    304) printf "Not Modified" ;;
    305) printf "Use Proxy" ;;
    307) printf "Temporary Redirect" ;;
    308) printf "Permanent Redirect" ;;

    400) printf "Bad Request" ;;
    401) printf "Unauthorized" ;;
    402) printf "Payment Required" ;;
    403) printf "Forbidden" ;;
    404) printf "Not Found" ;;
    405) printf "Method Not Allowed" ;;
    406) printf "Not Acceptable" ;;
    407) printf "Proxy Authentication Required" ;;
    408) printf "Request Timeout" ;;
    409) printf "Conflict" ;;
    410) printf "Gone" ;;
    411) printf "Length Required" ;;
    412) printf "Precondition Failed" ;;
    413) printf "Payload Too Large" ;;
    414) printf "URI Too Long" ;;
    415) printf "Unsupported Media Type" ;;
    416) printf "Range Not Satisfiable" ;;
    417) printf "Expectation Failed" ;;
    418) printf "I'm a Teapot" ;;
    421) printf "Misdirected Request" ;;
    422) printf "Unprocessable Content" ;;
    423) printf "Locked" ;;
    424) printf "Failed Dependency" ;;
    425) printf "Too Early" ;;
    426) printf "Upgrade Required" ;;
    428) printf "Precondition Required" ;;
    429) printf "Too Many Requests" ;;
    431) printf "Request Header Fields Too Large" ;;
    451) printf "Unavailable For Legal Reasons" ;;

    500) printf "Internal Server Error" ;;
    501) printf "Not Implemented" ;;
    502) printf "Bad Gateway" ;;
    503) printf "Service Unavailable" ;;
    504) printf "Gateway Timeout" ;;
    505) printf "HTTP Version Not Supported" ;;
    506) printf "Variant Also Negotiates" ;;
    507) printf "Insufficient Storage" ;;
    508) printf "Loop Detected" ;;
    510) printf "Not Extended" ;;
    511) printf "Network Authentication Required" ;;

    *)
        printf "Unknown Status"
        ;;
esac

}   


reqAcceptsHtml() {
    local request="$1"
    local accept

    accept="$(ParseBashletRequestHeader "$request" 'Accept')"

    [[ "$accept" == *text/html* ]]
}