#!/usr/bin/bash


# A collection of helper functions to simplify the process of working with 
# Mock API collections and their constituent endpoints, including the ability 
# to load and parse Mock API collections from JSON files, map request paths to 
# specific Mock API endpoints, and facilitate GET and POST request/response cycles 
# to those endpoints.

#Reads a Mock API collection from a JSON file and returns the parsed JSON object.
ReadMockAPICollection() {
    path="$1"
    jq -r '.' "$path"
}


# reads a specific value from the JSON Mock API collection using jq a reference
# to the Mock API Collection JSON must be provided as the first argument, and the key to read 
# must be provided as the second argument.
ParseMockAPICollectionField() {
    local json="$1"
    local path="$2"
    jq -cr "$path" <<< "$json"
}


SetMockAPICollectionField() {
    local json="$1"
    local path="$2"
    local value="$3"
    jq -cr --arg path "$path" --arg value "$value" 'setpath($path[1:] | split("." ); $value)' <<< "$json"
}


   
