#!/bin/bash

# import the handler utility functions, which are used by this handler to perform common tasks such as route resolution and response generation.
source "${SCRIPT_DIR}/res/handlers/internal/utils/handler-utils"

# vars passed into us from our parent root-handler
FULL_PATH="$1"
METHOD="$2"
PROTOCOL="$3"
RELATIVE_PATH="$4"
REQUEST_JSON_OBJECT="$5"


handleRequest(){

  Log "INFO" "system-handler: Received a request associated with (relative) path '$RELATIVE_PATH', processing..."

   # issue a call into our utility method to attempt to resolve route for the (relative) path 
   # provided to us by the root handler, which will have stripped the base path associated with 
   # this handler (i.e "/sys") from the original request path, we also taking care to pass in 
   # the path to THIS handlers routes config
   local config_path="${SCRIPT_DIR}/res/handlers/sys/system-handler-routes.json"
   route_info=$(ResolveRouteFromPath "$RELATIVE_PATH" "$config_path")

   # where we have found a matching route, call into our utility function to handle the request 
   # according to it declared route type, otherwise dispatch an appropriate error response.
   if [[ -n "$route_info" ]]; then
       HandleRequestAccordingToRoute "$route_info" "$RELATIVE_PATH" "$METHOD" "$PROTOCOL" "$REQUEST_JSON_OBJECT"
   else
     DispatchErrorResponse 404 "The requested resource was not found" "application/json" "$FULL_PATH" "$METHOD" "$REQUEST_JSON_OBJECT"
   fi


}

handleRequest
