#!/bin/bash

#utils to support the various bashlet operations, including synchronized local file system read and write,etc.
echo "BashletContext: Loaded BashletContext helper/utility functions... " >&2



# constructs a baseline/default bashlet response object in JSON format, which will be 
# returned to the caller, as-is, where the bashlet function being invoked does not 
# explicitly augment the response object via the various setter functions provided.
# Under normal circumstances, it is expected that the bashlet function being invoked will 
# augment the default response object with the appropriate status code, headers, content type 
# and body content, as appropriate for the specific request being handled.
BuildDefaultBashletResponseObject() {
  local status_code="$1"
  local headers="$2"
  local content_type="$3"
  local content="$4"    
 
  

  # construct a default bashlet response object in JSON format, which will be returned to the caller.
  jq -n --arg status_code "$status_code" \
        --arg status_message "$(GetStatusMsgForCode $status_code)" \
        --argjson headers "$headers" \
        --arg content_type "$content_type" \
        --arg content "$content" \
        '{
          status_code: ($status_code | tonumber),
          status_message: $status_message,
          headers: $headers,
          content_type: $content_type,
          body: $content
        }'
}

# constructs a default bashlet error response object in JSON format, which will be automatically returned where the
# BashletEngine encounters an error while attempting to invoke a target function, defined in a bashlet 
# such as when the specified function or the entire bashlet is not found or if the function fails to 
# execute successfully. User may also utilise this function within their own bashlet functions to 
# return a standard error response to the client, as necessary.
# Note: this function ONLY constructs (and returns) the error response object to dispatch the 
# error response to the client, use the DispatchBashletResponse function taking care to pass in the error response 
# object returned by this function.
BuildBashletErrorResponse(){
    
  local status_code="$1"
  local content="$2"

  # construct a default bashlet error response object in JSON format, which will be returned to the caller.
  BuildDefaultBashletResponseObject "$status_code" '{}' 'text/html' "$content"
}

# converts the provided bashlet response object into a standard HTTP response and dispatches it 
# to the caller.
DispatchBashletResponse(){

    local responseObject="$1"
    local status_code=$(jq -r '.status_code' <<< "$responseObject")
    local status_message=$(jq -r '.status_message' <<< "$responseObject")
    local headers=$(jq -r '.headers' <<< "$responseObject")
    local content_type=$(jq -r '.content_type' <<< "$responseObject")
    local content=$(jq -r '.body' <<< "$responseObject")

     printf "HTTP/1.1 $status_code $status_message\r\n"
     printf "Content-Type: %s\r\n" "$content_type"
     printf "Content-Length: %s\r\n" "${#content}"
     printf "Connection: close\r\n"
     printf "\r\n"
     printf "%s" "$content"

}






# -----------------------------------------------------public bashlet request object parsing functions---------------------------------------------------

ParseBashletRequestMethod() {
  local request="$1"
  jq -r '.method' <<< "$request"
}

ParseBashletRequestPath() {
  local request="$1"
  jq -r '.path' <<< "$request"
}

ParseBashletRequestProtocol() {
  local request="$1"
  jq -r '.protocol' <<< "$request"
}

ParseBashletRequestHeaders() {
  local request="$1"
  jq -r '.headers' <<< "$request"
}

ParseBashletRequestHeader() {
  local request="$1"
  local header_name="$2"
  jq -r --arg header_name "$header_name" '.headers[$header_name] // empty' <<< "$request"
}

ParseBashletRequestQueryString() {
  local request="$1"
  jq -r '.query_string' <<< "$request"
}


ParseBashletRequestQueryStringParam() {
  local request="$1"
  local parameter_name="$2"
  jq -r --arg parameter_name "$parameter_name" '.query_string[$parameter_name] // empty' <<< "$request"
}

ParseBashletRequestBody() {
  local request="$1"
  jq -r '.body' <<< "$request"
}

# -----------------------------------------------------public bashlet response setter functions---------------------------------------------------

# sets the status code of the provided bashlet response object to the specified value; this will
# also automatically set the status message to the standard message associated with the specified status code.
SetBashletResponseStatusCode() {
  local -n responseObject="$1"
  local status_code="$2"
  responseObject="$(jq --argjson status_code "$status_code" '.status_code = $status_code' <<< "$responseObject")"
  responseObject="$(jq --arg status_message "$(GetStatusMsgForCode $status_code)" '.status_message = $status_message' <<< "$responseObject")"
}

# sets the status message of the provided bashlet response object to the specified value.
# for standard HTTP status codes, this will be automatically set by the SetBashletResponseStatusCode function
# and thus it should not be necessary to call this function directly unless you wish to override the standard status message.
SetBashletResponseStatusMessage() {
  local -n responseObject="$1"
  local status_message="$2"
  responseObject="$(jq --arg status_message "$status_message" '.status_message = $status_message' <<< "$responseObject")"
}

# sets the headers of the provided bashlet response object to the specified name/value pair; 
# this will overwrite any existing header with the same name.
SetBashletResponseHeader() {
  local -n responseObject="$1"
  local header_name="$2"
  local header_value="$3"
  responseObject="$(jq --arg header_name "$header_name" --arg header_value "$header_value" '.headers[$header_name] = $header_value' <<< "$responseObject")"
}

# sets the content type of the provided bashlet response object to the specified value.
SetBashletResponseContentType() {
  local -n responseObject="$1"
  local content_type="$2"
  responseObject="$(jq --arg content_type "$content_type" '.content_type = $content_type' <<< "$responseObject")"
}

# sets the body of the provided bashlet response object to the specified value.
SetBashletResponseBody() {
  local -n responseObject="$1"
  local body="$2"
  responseObject="$(jq --arg body "$body" '.body = $body' <<< "$responseObject")"

  # if this is a JSON response, as determined by the body starting with '{' or '[', 
  # then we will also set the content type to application/json, unless this has already set,
  # otherwise we will leave the content type as-is, as it may have been set to something else 
  # by the caller where this not the case the default content type is text/html, which is set 
  # when the response object is first constructed.
  if [[ "$body" == \{* || "$body" == \[* ]]; then
    local current_content_type
    current_content_type=$(jq -r '.content_type' <<< "$responseObject")
    if [[ "$current_content_type" != "application/json" ]]; then
      SetBashletResponseContentType "$responseObject" "application/json"
    fi
  fi  


}



# ------------------------------------------------ public generic utility functions ---------------------------------------------------

StripPrefixFromBashletPath() {
    local path="$1"
    local prefix="$2"

    if [[ "$path" == "$prefix" ]]; then
        echo ""
    elif [[ "$path" == "$prefix"/* ]]; then
        echo "${path#"$prefix"/}"
    else
        echo "$path"
    fi
}

EnsureLeadingSlash() {
    local path="$1"

    [[ "$path" == /* ]] || path="/$path"

    printf '%s' "$path"
}


GetStatusMsgForCode() {

    local status_code="$1"

    case "$status_code" in
    100) printf "Continue" ;;
    101) printf "Switching Protocols" ;;
    102) printf "Processing" ;;
    103) printf "Early Hints" ;;

    200) printf "OK" ;;
    201) printf "Created" ;;
    202) printf "Accepted" ;;
    203) printf "Non-Authoritative Information" ;;
    204) printf "No Content" ;;
    205) printf "Reset Content" ;;
    206) printf "Partial Content" ;;
    207) printf "Multi-Status" ;;
    208) printf "Already Reported" ;;
    226) printf "IM Used" ;;

    300) printf "Multiple Choices" ;;
    301) printf "Moved Permanently" ;;
    302) printf "Found" ;;
    303) printf "See Other" ;;
    304) printf "Not Modified" ;;
    305) printf "Use Proxy" ;;
    307) printf "Temporary Redirect" ;;
    308) printf "Permanent Redirect" ;;

    400) printf "Bad Request" ;;
    401) printf "Unauthorized" ;;
    402) printf "Payment Required" ;;
    403) printf "Forbidden" ;;
    404) printf "Not Found" ;;
    405) printf "Method Not Allowed" ;;
    406) printf "Not Acceptable" ;;
    407) printf "Proxy Authentication Required" ;;
    408) printf "Request Timeout" ;;
    409) printf "Conflict" ;;
    410) printf "Gone" ;;
    411) printf "Length Required" ;;
    412) printf "Precondition Failed" ;;
    413) printf "Payload Too Large" ;;
    414) printf "URI Too Long" ;;
    415) printf "Unsupported Media Type" ;;
    416) printf "Range Not Satisfiable" ;;
    417) printf "Expectation Failed" ;;
    418) printf "I'm a Teapot" ;;
    421) printf "Misdirected Request" ;;
    422) printf "Unprocessable Content" ;;
    423) printf "Locked" ;;
    424) printf "Failed Dependency" ;;
    425) printf "Too Early" ;;
    426) printf "Upgrade Required" ;;
    428) printf "Precondition Required" ;;
    429) printf "Too Many Requests" ;;
    431) printf "Request Header Fields Too Large" ;;
    451) printf "Unavailable For Legal Reasons" ;;

    500) printf "Internal Server Error" ;;
    501) printf "Not Implemented" ;;
    502) printf "Bad Gateway" ;;
    503) printf "Service Unavailable" ;;
    504) printf "Gateway Timeout" ;;
    505) printf "HTTP Version Not Supported" ;;
    506) printf "Variant Also Negotiates" ;;
    507) printf "Insufficient Storage" ;;
    508) printf "Loop Detected" ;;
    510) printf "Not Extended" ;;
    511) printf "Network Authentication Required" ;;

    *)
        printf "Unknown Status"
        ;;
esac

}   