#!/bin/bash

#utils to support the various bashlet operations, including synchronized local file system read and write,etc.
echo "BashletContext: Loaded BashletContext helper/utility functions... " >&2


# souce the mime-utils library, which provides a set of utility functions for working with MIME types.
source "${SCRIPT_DIR}/res/utils/mime-utils"

# constructs a baseline/default bashlet response object in JSON format, which will be 
# returned to the caller, as-is, where the bashlet function being invoked does not 
# explicitly augment the response object via the various setter functions provided.
# Under normal circumstances, it is expected that the bashlet function being invoked will 
# augment the default response object with the appropriate status code, headers, content type 
# and body content, as appropriate for the specific request being handled.
BuildDefaultBashletResponseObject() {
  local status_code="$1"
  local headers="$2"
  local content_type="$3"
  local content="$4"    
 
  

  # construct a default bashlet response object in JSON format, which will be returned to the caller.
  jq -n --arg status_code "$status_code" \
        --arg status_message "$(GetStatusMsgForCode $status_code)" \
        --argjson headers "$headers" \
        --arg content_type "$content_type" \
        --arg content "$content" \
        '{
          status_code: ($status_code | tonumber),
          status_message: $status_message,
          headers: $headers,
          content_type: $content_type,
          body: $content
        }'
}

# constructs a default bashlet error response object in JSON format, which will be automatically returned where the
# BashletEngine encounters an error while attempting to invoke a target function, defined in a bashlet 
# such as when the specified function or the entire bashlet is not found or if the function fails to 
# execute successfully. User may also utilise this function within their own bashlet functions to 
# return a standard error response to the client, as necessary.
# Note: this function ONLY constructs (and returns) the error response object to dispatch the 
# error response to the client, use the DispatchBashletResponse function taking care to pass in the error response 
# object returned by this function.
BuildBashletErrorResponse(){
    
  local status_code="$1"
  local content="$2"
  local short_content_type="$3"  # short contnt type is just the second part of the content type, e.g: html for text/html or json for application/json, etc.

  # if the short content type is not provided, we will default to html.
  if [[ -z $short_content_type ]]; then
      short_content_type=".html"
  fi

  # next we use yhe short content type (case insensitive) to look up the full content type, via the mime-utils helper functions.
  local content_type
  content_type=$(getMimeType ".$short_content_type")


  # the error code MUST start with a 4 where this not the case we return a 500 internal server error,
  # as this is an unexpected error condition.
  if [[ ! "$status_code" =~ ^4[0-9]{2}$ ]]; then
      status_code=500
      content="Internal Server Error - An attempt was made to build a bashlet error response with a non-4xx status code (i.e: $1), this is not permitted. The status code has been automatically set to 500 Internal Server Error. The original error message was: $content"
  fi

  # construct a default bashlet error response object in JSON format, which will be returned to the caller.
  BuildDefaultBashletResponseObject "$status_code" '{}' "$content_type" "$content"
}

# converts the provided bashlet response object into a standard HTTP response and dispatches it 
# to the caller. A special header is also set in the response to indicate that its COMPLETED. 
# this will prevent the BashletEngine from attempting to send a second response to the client.
DispatchBashletResponse(){

    local responseObject="$1"
    local status_code=$(jq -r '.status_code' <<< "$responseObject")
    local status_message=$(jq -r '.status_message' <<< "$responseObject")
    local headers=$(jq -c '.headers // {}' <<< "$responseObject")
    local content_type=$(jq -r '.content_type' <<< "$responseObject")
    local content=$(jq -r '.body' <<< "$responseObject")

    printf "HTTP/1.1 $status_code $status_message\r\n"
    printf "Content-Type: %s\r\n" "$content_type"
    printf "Content-Length: %s\r\n" "${#content}"

    while IFS= read -r header_line; do
      [[ -z "$header_line" ]] && continue
      printf "%s\r\n" "$header_line"
    done < <(jq -r 'to_entries[]? | "\(.key): \(.value)"' <<< "$headers")

     printf "Connection: close\r\n"
     printf "\r\n"
     printf "%s" "$content"

     # grab reference to the response object and set the X-Request-Completed header to true, 
     # this will signal to the BashletEngine that the request has been completed and that it should 
     # not attempt to send a second response to the client.
     local header_name="X-Request-Completed"
     local header_value="true"
     responseObject="$(jq --arg header_name "$header_name" --arg header_value "$header_value" '.headers[$header_name] = $header_value' <<< "$responseObject")"
     bashletResponse="$responseObject" # update the response object in the BashletEngine context to include the X-Request-Completed header, this will prevent the BashletEngine from attempting to send a second response to the client.
    
     #echo "RESPONSE OBJECT FROM INSIDE DISPATCH FUNCTION: $responseObject" >&2
     #echo "***Response variable name: $bashletResponseVarName" >&2
     #local -n responseObject="$bashletResponseVarName"
     #responseObject="$(SetBashletResponseHeader  "$responseObject" 'X-Request-Completed' 'true')"

   

}

DispatchBashletRedirectResponse() {
    local redirect_url="$1"
    local status_code=302
    local status_message="$(GetStatusMsgForCode $status_code)"
    local headers="{\"Location\": \"$redirect_url\"}"
    local content_type="text/html"
    local content="<html><body><p>$status_code $status_message</p><p>Redirecting to <a href=\"$redirect_url\">$redirect_url</a></p></body></html>"

    local responseObject
    responseObject=$(BuildDefaultBashletResponseObject "$status_code" "$headers" "$content_type" "$content")
    DispatchBashletResponse "$responseObject"
}






# -----------------------------------------------------public bashlet request object parsing functions---------------------------------------------------

ParseBashletRequestMethod() {
  local request="$1"
  jq -r '.method' <<< "$request"
}

ParseBashletRequestPath() {
  local request="$1"
  jq -r '.path' <<< "$request"
}

ParseBashletRequestProtocol() {
  local request="$1"
  jq -r '.protocol' <<< "$request"
}

ParseBashletRequestHeaders() {
  local request="$1"
  jq -r '.headers' <<< "$request"
}

ParseBashletRequestHeader() {
  local request="$1"
  local header_name="$2"
  jq -r --arg header_name "$header_name" '.headers[$header_name] // empty' <<< "$request"
}

ParseBashletRequestQueryString() {
  local request="$1"
  jq -r '.query_string' <<< "$request"
}


ParseBashletRequestQueryStringParam() {
  local request="$1"
  local parameter_name="$2"
  jq -r --arg parameter_name "$parameter_name" '.query_string[$parameter_name] // empty' <<< "$request"
}

ParseBashletRequestBody() {
  local request="$1"
  jq -r '.body' <<< "$request"
}

SetRequestHeader() {
  local request="$1"
  local header_name="$2"
  local header_value="$3"
  jq -c --arg header_name "$header_name" --arg header_value "$header_value" '.headers[$header_name] = $header_value' <<< "$request"
}

DeleteRequestHeader() {
  local request="$1"
  local header_name="$2"
  jq -c --arg header_name "$header_name" 'del(.headers[$header_name])' <<< "$request"
}

# -----------------------------------------------------public bashlet response setter functions---------------------------------------------------

# sets the status code of the provided bashlet response object to the specified value; this will
# also automatically set the status message to the standard message associated with the specified status code.
SetBashletResponseStatusCode() {
  local -n responseObject="$1"
  local status_code="$2"
  responseObject="$(jq --argjson status_code "$status_code" '.status_code = $status_code' <<< "$responseObject")"
  responseObject="$(jq --arg status_message "$(GetStatusMsgForCode $status_code)" '.status_message = $status_message' <<< "$responseObject")"
}

# sets the status message of the provided bashlet response object to the specified value.
# for standard HTTP status codes, this will be automatically set by the SetBashletResponseStatusCode function
# and thus it should not be necessary to call this function directly unless you wish to override the standard status message.
SetBashletResponseStatusMessage() {
  local -n responseObject="$1"
  local status_message="$2"
  responseObject="$(jq --arg status_message "$status_message" '.status_message = $status_message' <<< "$responseObject")"
}

# sets the headers of the provided bashlet response object to the specified name/value pair; 
# this will overwrite any existing header with the same name.
SetBashletResponseHeader() {
  local -n responseObject="$1"
  local header_name="$2"
  local header_value="$3"
  responseObject="$(jq --arg header_name "$header_name" --arg header_value "$header_value" '.headers[$header_name] = $header_value' <<< "$responseObject")"
}

# sets the content type of the provided bashlet response object to the specified value.
SetBashletResponseContentType() {
  local -n responseObject="$1"
  local content_type="$2"
  responseObject="$(jq --arg content_type "$content_type" '.content_type = $content_type' <<< "$responseObject")"
}

# sets the body of the provided bashlet response object to the specified value.
SetBashletResponseBody() {
  local -n responseObject="$1"
  local body="$2"
  responseObject="$(jq --arg body "$body" '.body = $body' <<< "$responseObject")"

  # if this is a JSON response, as determined by the body starting with '{' or '[', 
  # then we will also set the content type to application/json, unless this has already set,
  # otherwise we will leave the content type as-is, as it may have been set to something else 
  # by the caller where this not the case the default content type is text/html, which is set 
  # when the response object is first constructed.
  if [[ "$body" == \{* || "$body" == \[* ]]; then
    local current_content_type
    current_content_type=$(jq -r '.content_type' <<< "$responseObject")
    if [[ "$current_content_type" != "application/json" ]]; then
      responseObject="$(jq --arg content_type "application/json" '.content_type = $content_type' <<< "$responseObject")"
    fi
  fi  


}

# parses the provided bashlet response object and returns the value of the specified header, or an empty string if the header is not present.
ParseBashletResponseHeader() {
  local response="$1"
  local header_name="$2"
  jq -r --arg header_name "$header_name" '.headers[$header_name] // empty' <<< "$response"
}




# -----------------------------------------------------public JSON utility functions---------------------------------------------------

ParseJSONField() {
    local json="$1"
    local path="$2"
    jq -cr "$path" <<< "$json"
}

IsJSON() {
    jq -e . >/dev/null 2>&1 <<< "$1"
}

SetJSONField() {

    local json="$1"
    local path="$2"
    local value="$3"

    if IsJSON "$value"; then

        jq -c \
           --argjson value "$value" \
           "$path = \$value" <<< "$json"

    else

        jq -c \
           --arg value "$value" \
           "$path = \$value" <<< "$json"

    fi
}

SetJSONBoolean() {

    local json="$1"
    local path="$2"
    local value="$3"

    case "$value" in
        true|false)
            ;;
        *)
            echo "SetJSONBoolean: value must be 'true' or 'false'" >&2
            return 1
            ;;
    esac

    jq -c \
       --argjson value "$value" \
       "$path = \$value" <<< "$json"
}

SetJSONNumber() {

    local json="$1"
    local path="$2"
    local value="$3"

    if ! jq -en --arg value "$value" '$value | tonumber' >/dev/null 2>&1; then
        echo "SetJSONNumber: '$value' is not a valid number" >&2
        return 1
    fi

    jq -c \
       --argjson value "$value" \
       "$path = \$value" <<< "$json"
}

SetJSONString() {

    local json="$1"
    local path="$2"
    local value="$3"

    jq -c \
       --arg value "$value" \
       "$path = \$value" <<< "$json"
}

AppendJSONArrayItem() {
    local json="$1"
    local value="$2"

    if IsJSON "$value"; then
        jq -c --argjson v "$value" '. += [$v]' <<< "$json"
    else
        jq -c --arg v "$value" '. += [$v]' <<< "$json"
    fi
}



# ------------------------------------------------ public generic utility functions ---------------------------------------------------

# Signals to the BashletEngine (via setting of the X-Forward-To header) that the current request 
# is to be forwarded to the specified path, this will cause the BashletEngine to omit sending a 
# direct response to the client and instead forward the request to the specified path.
# This function is intended to be called from within the context of a bashlet function, where there is
# a requirement to forward the request to another bashlet or static resource.
ForwardBashletRequest(){
   forward_to_path="$1"

   # here we merely append the X-FORWARD-TO header to the request, this will signal that the BashletEngine
   # that the request is required to be forwarded and will preclude it from dispatching a direct response to the client.
   # The BashletEngine stores the request struct under $bashletRequest
   bashletRequest="$(SetRequestHeader "$bashletRequest" 'X-Forward-To' "$forward_to_path")"

}


# Actually undertakes the work of fowarding the request to the specified path, by delegating the request to the root-handler, 
# which will cause the request to re-enter the Mocktail Server routing system, as if it was received, afresh, from a remote client.
DoForwardBashletRequest(){

  # grab reference to the request and extract the X-Forward-To header, which will contain the path 
  # to which the request is to be forwarded. The bashlet engine always stores the current request under 
  # $bashletRequest.
  forwardPath="$(ParseBashletRequestHeader "$bashletRequest" 'X-Forward-To')"
  if [[ -z "$forwardPath" ]]; then
      echo "DoForwardBashletRequest: No X-Forward-To header found in request, cannot forward request." >&2
      return 1
  fi

  # next parse the rest of the requisite details that we'll need to delegate the request to the root-handler...
  reqMethod="$(ParseJSONField "$bashletRequest" '.method')"
  reqProtocol="$(ParseJSONField "$bashletRequest" '.protocol')"
  reqHost="$(ParseBashletRequestHeader "$bashletRequest" 'Host')"  # required for the X-Forwarded-For header we'll ultimately append to the request.
  reqPath="$(ParseJSONField "$bashletRequest" '.path')"

  
  # attempt to obtain the X-Forwarded-For header from the request, this may have been set by a prior forward,
  # where it exist we will append the current non-forwarded path to it. Conversely where it does not exist
  # we create the header and set it to the current, non-forwarded path.
  fullForwardForPath="$reqHost$reqPath"
  xForwardedFor="$(ParseBashletRequestHeader "$bashletRequest" 'X-Forwarded-For')"
  if [[ -n "$xForwardedFor" ]]; then
      xForwardedFor="$xForwardedFor, $fullForwardForPath"
  else
    bashletRequest="$(SetRequestHeader "$bashletRequest" 'X-Forwarded-For' "$fullForwardForPath")"
  fi
       
  # now we've set the forwarded for header to the old path update the bashlet request path to the new forward path.
  bashletRequest="$(SetJSONField "$bashletRequest" '.path' "$forwardPath")"

  # delete the X-Forward-To header from the request, as it is no longer required, and we don't want to pass it on to the next handler
  # as this may (where the forward is to another bashlet) cause a forwarding storm, where the request would be forwarded in a loop.
  bashletRequest="$(DeleteRequestHeader "$bashletRequest" 'X-Forward-To')"

  # finally delegate the request to the root-handler, which will cause the request to re-enter the Mocktail Server 
  # routing system, as if it was received, afresh, from a remote client.
  DelegateRequest "$forwardPath" "$reqMethod" "$reqProtocol" "$bashletRequest"-

}


# Immediately sends an error response to the client, using the provided status code, content and short content type.
SendErrorResponse() {
    local status_code="$1"
    local content="$2"
    local short_content_type="$3"

    local error_response
    error_response=$(BuildBashletErrorResponse "$status_code" "$content" "$short_content_type")
    DispatchBashletResponse "$error_response" 
   
}

requestAcceptsHtml() {
    local request="$1"
    local accept

    accept="$(ParseBashletRequestHeader "$request" 'Accept')"

    [[ "$accept" == *text/html* ]]
}


StripPrefixFromBashletPath() {
    local path="$1"
    local prefix="$2"

    if [[ "$path" == "$prefix" ]]; then
        echo ""
    elif [[ "$path" == "$prefix"/* ]]; then
        echo "${path#"$prefix"/}"
    else
        echo "$path"
    fi
}

EnsureLeadingSlash() {
    local path="$1"

    [[ "$path" == /* ]] || path="/$path"

    printf '%s' "$path"
}



GetStatusMsgForCode() {

    local status_code="$1"

    case "$status_code" in
    100) printf "Continue" ;;
    101) printf "Switching Protocols" ;;
    102) printf "Processing" ;;
    103) printf "Early Hints" ;;

    200) printf "OK" ;;
    201) printf "Created" ;;
    202) printf "Accepted" ;;
    203) printf "Non-Authoritative Information" ;;
    204) printf "No Content" ;;
    205) printf "Reset Content" ;;
    206) printf "Partial Content" ;;
    207) printf "Multi-Status" ;;
    208) printf "Already Reported" ;;
    226) printf "IM Used" ;;

    300) printf "Multiple Choices" ;;
    301) printf "Moved Permanently" ;;
    302) printf "Found" ;;
    303) printf "See Other" ;;
    304) printf "Not Modified" ;;
    305) printf "Use Proxy" ;;
    307) printf "Temporary Redirect" ;;
    308) printf "Permanent Redirect" ;;

    400) printf "Bad Request" ;;
    401) printf "Unauthorized" ;;
    402) printf "Payment Required" ;;
    403) printf "Forbidden" ;;
    404) printf "Not Found" ;;
    405) printf "Method Not Allowed" ;;
    406) printf "Not Acceptable" ;;
    407) printf "Proxy Authentication Required" ;;
    408) printf "Request Timeout" ;;
    409) printf "Conflict" ;;
    410) printf "Gone" ;;
    411) printf "Length Required" ;;
    412) printf "Precondition Failed" ;;
    413) printf "Payload Too Large" ;;
    414) printf "URI Too Long" ;;
    415) printf "Unsupported Media Type" ;;
    416) printf "Range Not Satisfiable" ;;
    417) printf "Expectation Failed" ;;
    418) printf "I'm a Teapot" ;;
    421) printf "Misdirected Request" ;;
    422) printf "Unprocessable Content" ;;
    423) printf "Locked" ;;
    424) printf "Failed Dependency" ;;
    425) printf "Too Early" ;;
    426) printf "Upgrade Required" ;;
    428) printf "Precondition Required" ;;
    429) printf "Too Many Requests" ;;
    431) printf "Request Header Fields Too Large" ;;
    451) printf "Unavailable For Legal Reasons" ;;

    500) printf "Internal Server Error" ;;
    501) printf "Not Implemented" ;;
    502) printf "Bad Gateway" ;;
    503) printf "Service Unavailable" ;;
    504) printf "Gateway Timeout" ;;
    505) printf "HTTP Version Not Supported" ;;
    506) printf "Variant Also Negotiates" ;;
    507) printf "Insufficient Storage" ;;
    508) printf "Loop Detected" ;;
    510) printf "Not Extended" ;;
    511) printf "Network Authentication Required" ;;

    *)
        printf "Unknown Status"
        ;;
esac

}   