#!/bin/bash

echo "root-handler: Received a request, processing..." >&2

if [[ -n "$MAX_PROCESSES" ]]; then
  current_processes=$(pgrep -fc "root-handler")
  echo "root-handler: Current processes: $current_processes" >&2
  if (( current_processes > MAX_PROCESSES )); then
    echo "root-handler: Maximum process limit reached ($current_processes), refusing connection." >&2
    exit 1
  fi
fi

read -r -t 5 method path protocol || exit 1

#route request based on path, taking care to pass in the request line to the subhandler
case "$path" in
  "/sample" | /sample/*)
    echo "root-handler: Routing to sample-sub-handler for path: $path" >&2
   "${SCRIPT_DIR}/res/handlers/usr/sample-sub-handler" \
    "$method" "$path" "$protocol"
    ;;
  *)
    echo "root-handler: No specific handler for path: $path, sending default response." >&2
    body='{"status":"Not Found","method":"'"$method"'","path":"'"$path"'","protocol":"'"$protocol"'"}'
    printf "HTTP/1.1 404 Not Found\r\n"
    printf "Content-Type: application/json\r\n"
    printf "Content-Length: %s\r\n" "${#body}"
    printf "Connection: close\r\n"
    printf "\r\n"
    printf "%s" "$body"
    echo "root-handler: Default response sent for path: $path, closing connection." >&2
    ;;
esac


#body='{"status":"ok","method":"'"$method"'","path":"'"$path"'","protocol":"'"$protocol"'"}'
#printf "HTTP/1.1 200 OK\r\n"
#printf "Content-Type: application/json\r\n"
#printf "Content-Length: %s\r\n" "${#body}"
#printf "Connection: close\r\n"
#printf "\r\n"
#printf "%s" "$body"

# echo "root-handler: Response sent, closing connection." >&2
